import { describe, it, expect } from 'vitest';
import { Fernet } from './fernet.js';
import { execSync } from 'node:child_process';
import { join } from 'node:path';
import { Buffer } from 'node:buffer';

describe('Python Compatibility', () => {
    // Path to the python script
    // We assume it's in the root, and tests run from root
    const pythonScript = join(process.cwd(), 'verify_compat.py');

    // Check if python is available and has cryptography
    let pythonAvailable = false;
    try {
        execSync(`python "${pythonScript}" generate`, { stdio: 'pipe' });
        pythonAvailable = true;
    } catch (e) {
        console.warn("Python compatibility test skipped: Python or cryptography module not found.");
    }

    if (pythonAvailable) {
        it('decrypts a token generated by Python', () => {
            const output = execSync(`python "${pythonScript}" generate`).toString();
            const data = JSON.parse(output);

            const f = new Fernet(data.key);
            const decrypted = f.decrypt(data.token);

            expect(decrypted.toString('utf-8')).toBe(data.plaintext);
        });

        it('encrypts a token that Python can decrypt', async () => {
            // 1. Generate Key in Node (or reuse one, let's generate our own)
            // We need a helper to generate key since it's not a public static method yet, 
            // but we can just use crypto directly or use a fixed one.
            // Let's use a fixed one for simplicity or generate one.
            const { randomBytes } = await import('node:crypto');
            const key = randomBytes(32).toString('base64').replace(/\+/g, '-').replace(/\//g, '_');

            const f = new Fernet(key);
            const plaintext = "Hello from TypeScript!";
            const token = f.encrypt(Buffer.from(plaintext));

            // 2. call Python to decrypt
            const input = JSON.stringify({ key, token });
            // Use python script 'decrypt' command
            // We need to write to stdin. 
            // execSync with input option is available in Node? no, 'input' option exists in execSync options.

            const result = execSync(`python "${pythonScript}" decrypt`, { input }).toString();
            const data = JSON.parse(result);

            expect(data.plaintext).toBe(plaintext);
        });
    } else {
        it.skip('Python compatibility tests (requires python + cryptography)', () => { });
    }
});
